from .. import env

ADMIN_SYNC_CONFIG = env("ADMIN_SYNC_CONFIG")
ADMIN_SYNC_RESPONSE_HEADER = None
# these are actually used only in local development
ADMIN_SYNC_REMOTE_SERVER = env("ADMIN_SYNC_REMOTE_SERVER")
ADMIN_SYNC_REMOTE_ADMIN_URL = env("ADMIN_SYNC_REMOTE_ADMIN_URL")
ADMIN_SYNC_LOCAL_ADMIN_URL = env("ADMIN_SYNC_LOCAL_ADMIN_URL")
