# Generated by Django 5.2.1 on 2025-06-05 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flexform",
            options={"ordering": ("name",), "verbose_name": "Flex Form", "verbose_name_plural": "Flex Forms"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="validator",
            options={"ordering": ("name",), "verbose_name": "Validator", "verbose_name_plural": "Validators"},
        ),
    ]
