# Generated by Django 3.2.18 on 2023-04-03 08:53

import aurora.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_auto_20230321_0604"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexformfield",
            name="mapping",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="flexformfield",
            name="note",
            field=models.CharField(blank=True, help_text="Add here for the mapping", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="flexformfield",
            name="choices",
            field=models.CharField(
                blank=True, max_length=2000, null=True, validators=[aurora.core.models.ChoicesValidator]
            ),
        ),
    ]
