# Generated by Django 5.2 on 2025-04-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_alter_validator_options_alter_customfieldtype_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionset",
            name="columns",
            field=models.CharField(blank=True, default="", editable=False, max_length=20),
        ),
    ]
