[mypy]
python_version = "3.13"
mypy_path = ["fixtures/stubs-for-mypy"]
plugins = [
  "pydantic.mypy",
  "mypy_django_plugin.main",
  "tools.mypy_helpers.plugin",
]
files = ["."]
exclude = ["^.venv/", "^venv/", "^self-hosted/"]
