[project]
name = "aurora"
version = "0.1"
description = ""
readme = "README.md"
license = {text = "MIT"}

authors = [
    {name = "sax", email = "s.apostolico@gmail.com"},
    {name = "Domenico DiNicola", email = "dom.dinicola@gmail.com"},
]
requires-python = ">=3.12"
dependencies = [
    "Faker",
    "Markdown",
    "Pillow",
    "beautifulsoup4",
    "celery",
    "channels-redis",
    "channels[daphne]",
    "cryptography",
    "django-admin-extra-buttons",
    "django-admin-ordering",
    "django-admin-sync",
    "django-adminactions",
    "django-adminfilters",
    "django-anymail[mailjet]",
    "django-appconf",
    "django-bitfield",
    "django-click",
    "django-concurrency",
    "django-constance",
    "django-cors-headers",
    "django-csp",
    "django-debug-toolbar",
    "django-environ",
    "django-filter",
    "django-flags",
    "django-front-door",
    "django-hijack",
    "django-import-export",
    "django-jsoneditor",
    "django-mdeditor",
    "django-mptt",
    "django-picklefield",
    "django-pwa",
    "django-redis",
    "django-regex",
    "django-regex",
    "django-reversion",
    "django-reversion-compare",
    "django-simple-captcha",
    "django-simple-math-captcha",
    "django-smart-admin",
    "django-smart-env>=0.1.0",
    "django-strategy-field",
    "django-sysinfo",
    "django-tinymce",
    "django<5",
    "djangorestframework",
    "djangorestframework-datatables",
    "htmlmin",
    "jmespath",
    "jsonpickle",
    "natural-keys",
    "psycopg2-binary",
    "py-mini-racer",
    "pycryptodome",
    "pygments",
    "pyquery",
    "qrcode",
    "sentry-sdk",
    "setuptools>=75.6.0",
    "social-auth-app-django",
    "soupsieve",
    "sqlparse",
    "uwsgi",
]
name = "Aurora"
version = "0.1"
description = ""
readme = "README.md"
license = {text = "MIT"}


[tool.uv]
dev-dependencies = [
    "black<23.0.0,>=22.1.0",
    "coverage",
    "django-webtest<2.0.0,>=1.9.7",
    "factory-boy",
    "flake8",
    "flake8-html",
    "freezegun<2.0.0,>=1.2.2",
    "ipython",
    "isort<6.0.0,>=5.6.4",
    "pdbpp",
    "pre-commit",
    "pyflakes",
    "pytest<7.2",
    "pytest-asyncio",
    "pytest-coverage<1.0,>=0.0",
    "pytest-django<5.0.0,>=4.1.0",
    "pytest-echo",
    "pytest-html",
    "pytest-pythonpath<1.0.0,>=0.7.3",
    "pytest-selenium<3.0,>=2.0",
    "pytest-variables<3.0",
    "tox",
    "watchdog<3.0.0,>=2.1.6",
    "django-stubs[compatible-mypy]<2.0.0,>=1.16.0",
    "pytest-xdist>=3.6.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools]
packages = ["aurora", "dbtemplates"]

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.pytest_cache
  | \.tox
  | \.venv
  | ~build
  | build
  | ops
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 120
default_section = "THIRDPARTY"
known_first_party = []
known_django = "django"
sections = ["FUTURE","STDLIB","DJANGO","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
include_trailing_comma = true
skip = ["migrations", "snapshots", ".venv"]
