[project]
name = "aurora"
version = "0.1"
description = ""
readme = "README.md"
license = {text = "MIT"}

authors = [
    {name = "sax", email = "s.apostolico@gmail.com"},
    {name = "Domenico DiNicola", email = "dom.dinicola@gmail.com"},
]
requires-python = ">=3.12"
dependencies = [
    "Faker",
    "Markdown",
    "Pillow",
    "beautifulsoup4",
    "celery",
    "channels-redis",
    "channels[daphne]",
    "cryptography",
    "django-admin-extra-buttons",
    "django-admin-ordering",
    "django-admin-sync",
    "django-adminactions",
    "django-adminfilters",
    "django-anymail[mailjet]",
    "django-appconf",
    "django-bitfield",
    "django-click",
    "django-concurrency",
    "django-constance",
    "django-cors-headers",
    "django-csp",
    "django-debug-toolbar",
    "django-environ",
    "django-filter",
    "django-flags",
    "django-front-door",
    "django-hijack",
    "django-import-export",
    "django-jsoneditor",
    "django-mdeditor",
    "django-mptt",
    "django-picklefield",
    "django-pwa",
    "django-redis",
    "django-regex",
    "django-regex",
    "django-reversion",
    "django-reversion-compare",
    "django-simple-captcha",
    "django-simple-math-captcha",
    "django-smart-admin",
    "django-smart-env>=0.1.0",
    "django-strategy-field",
    "django-sysinfo",
    "django-tinymce",
    "django<5",
    "djangorestframework",
    "djangorestframework-datatables",
    "htmlmin",
    "jmespath",
    "jsonpickle",
    "natural-keys",
    "psycopg2-binary",
    "py-mini-racer",
    "pycryptodome",
    "pygments",
    "pyquery",
    "qrcode",
    "sentry-sdk",
    "setuptools",
    "social-auth-app-django",
    "soupsieve",
    "sqlparse",
    "uwsgi",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools]
packages = ["aurora", "dbtemplates"]


[tool.uv]
dev-dependencies = [
    "black<23.0.0,>=22.1.0",
    "coverage",
    "django-webtest<2.0.0,>=1.9.7",
    "factory-boy",
    "flake8",
    "flake8-html",
    "freezegun<2.0.0,>=1.2.2",
    "ipython",
    "isort<6.0.0,>=5.6.4",
    "pdbpp",
    "pre-commit",
    "pyflakes",
    "pytest<7.2",
    "pytest-asyncio",
    "pytest-coverage<1.0,>=0.0",
    "pytest-django<5.0.0,>=4.1.0",
    "pytest-echo",
    "pytest-html",
    "pytest-pythonpath<1.0.0,>=0.7.3",
    "pytest-selenium<3.0,>=2.0",
    "pytest-variables<3.0",
    "tox",
    "watchdog<3.0.0,>=2.1.6",
    "django-stubs[compatible-mypy]<2.0.0,>=1.16.0",
]

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | snapshots
  | __pypackages__
)/
'''

[tool.isort]
combine_as_imports = true
default_section = "THIRDPARTY"
include_trailing_comma = true
known_django = "django"
known_typing = ["typing"]
known_tests = ["unittest", "pytest"]
known_app = "aurora"
sections = ["FUTURE", 'TYPING', 'STDLIB',"TESTS",'DJANGO', 'FIRSTPARTY', 'THIRDPARTY','APP','LOCALFOLDER']
multi_line_output = 3
line_length = 120
balanced_wrapping = true
order_by_type = false
skip_glob = ["**/migrations/**"]
