# Generated by Django 5.2.1 on 2025-06-05 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuroraUser",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("username",), "verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
