# Generated by Django 5.2.13 on 2026-04-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0002_delete_aurorauser_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="azure_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
