# Generated by Django 5.2.13 on 2026-04-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0003_user_azure_id_user_display_name_user_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_modify_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
