# Generated by Django 5.0.11 on 2025-02-06 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0011_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuroraUser",
        ),
    ]
