# Generated by Django 5.2 on 2025-04-10 05:29

from django.db import migrations, models

import aurora.i18n.fields


class Migration(migrations.Migration):
    dependencies = [
        ("i18n", "0012_alter_message_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="auto",
            field=models.BooleanField(default=False, help_text="Is this message auto-generated?"),
        ),
        migrations.AlterField(
            model_name="message",
            name="draft",
            field=models.BooleanField(default=True, help_text="If draft the message is not used in translation"),
        ),
        migrations.AlterField(
            model_name="message",
            name="last_hit",
            field=models.DateTimeField(
                blank=True, help_text="Last time this translation hase been used message", null=True
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="locale",
            field=aurora.i18n.fields.LanguageField(
                choices=[
                    ("en-us", "English | English"),
                    ("ar-ae", " | عربيArabic"),
                    ("cs-cz", "čeština | Czech"),
                    ("de-de", "Deutsch | German"),
                    ("es-es", "Español | Spanish"),
                    ("fr-fr", "Français | French"),
                    ("hu-hu", "Magyar | Hungarian"),
                    ("it-it", "Italiano | Italian"),
                    ("pl-pl", "Polskie | Polish"),
                    ("pt-pt", "Português | Portuguese"),
                    ("ro-ro", "Română | Romanian"),
                    ("ru-ru", "Русский | Russian"),
                    ("si-si", "සිංහල | Sinhala"),
                    ("ta-ta", "தமிழ் | Tamil"),
                    ("uk-ua", "український | Ukrainian"),
                    ("hi-hi", "हिंदी | Hindi"),
                ],
                db_index=True,
                default="en-us",
                help_text="The locale of the message.",
                max_length=10,
                null=True,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="md5",
            field=models.CharField(
                help_text="Localised code of the message", max_length=512, unique=True, verbose_name="MD5"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="msgcode",
            field=models.CharField(
                help_text="Code of the message. It is shared between translations of same message.",
                max_length=512,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="msgid",
            field=models.TextField(db_index=True, help_text="Original message value"),
        ),
        migrations.AlterField(
            model_name="message",
            name="msgstr",
            field=models.TextField(blank=True, help_text="Localized Message content.", null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="used",
            field=models.BooleanField(default=True, help_text="Is this message used somewhere in Aurora?"),
        ),
    ]
