import uuid

from smart_env import SmartEnv


def parse_bookmarks(value: str) -> str:
    return "".join(value.split(r"\n"))


def parse_emails(value: str) -> list[tuple[str, str]]:
    admins = value.split(",")
    return [(a.split("@")[0].strip(), a.strip()) for a in admins if a.strip()]


OPTIONS = {
    "ADMINS": (
        parse_emails,
        "",
        "",
        False,
        "Comma-separated list of admin email addresses that receive error reports.",
    ),
    "ADMIN_SYNC_CONFIG": (
        str,
        "admin_sync.conf.DjangoConstance",
        "",
        False,
        "Django Admin Sync configuration class used to replicate admin content between instances.",
    ),
    "ADMIN_SYNC_LOCAL_ADMIN_URL": (
        str,
        "",
        "",
        False,
        "Local admin URL used by the admin sync engine when this instance acts as the origin.",
    ),
    "ADMIN_SYNC_REMOTE_ADMIN_URL": (
        str,
        "",
        "",
        False,
        "Remote admin URL that this instance syncs content from or to.",
    ),
    "ADMIN_SYNC_REMOTE_SERVER": (
        str,
        "",
        "",
        False,
        "Remote server name used to authenticate the admin sync engine.",
    ),
    "ALLOWED_HOSTS": (
        list,
        ["*"],
        "",
        False,
        "List of host/domain names that this Django site can serve. An empty list allows any host, "
        "which is unsafe in production.",
    ),
    "AZURE_AUTHORITY_HOST": (
        str,
        "",
        "",
        False,
        "Azure AD authority host used by the Microsoft Graph / social authentication flow.",
    ),
    "AZURE_CLIENT_ID": (str, "", "", False, "Azure AD application (client) ID used for social authentication."),
    "AZURE_CLIENT_SECRET": (str, "", "", False, "Azure AD application secret used for social authentication."),
    "AZURE_POLICY_NAME": (str, "", "", False, "Azure AD B2C policy name used during social authentication."),
    "AZURE_TENANT_ID": (str, "", "", False, "Azure AD tenant ID used for social authentication."),
    "AZURE_TRANSLATOR_KEY": (str, "", "", False, "Azure Translator service key used to translate form content."),
    "AZURE_TRANSLATOR_LOCATION": (str, "", "", False, "Azure Translator service region/location."),
    "BROKER_URL": (
        str,
        "redis://broker-url:6379",
        "",
        False,
        "Redis URL used by Dramatiq (async tasks and scheduled jobs).",
    ),
    "CELERY_BROKER_URL": (
        str,
        "",
        "",
        False,
        "Celery broker URL. Overrides BROKER_URL when the Celery worker is used.",
    ),
    "CACHE_DEFAULT": (
        str,
        "locmemcache://",
        "",
        True,
        "Django cache backend URL for the default cache. Required in production, e.g. redis://host:6379/0.",
    ),
    "CAPTCHA_TEST_MODE": (bool, "false", "", False, "If true, CAPTCHA validation always succeeds. Use in tests only."),
    "CHANNEL_LAYER": (
        str,
        "locmemcache://",
        "",
        True,
        "Channel layer backend URL for WebSocket support. In production use a shared Redis layer.",
    ),
    "CONSTANCE_DATABASE_CACHE_BACKEND": (
        str,
        "",
        "",
        False,
        "Cache backend name used by django-constance to cache database-backed settings.",
    ),
    "CORS_ALLOWED_ORIGINS": (
        list,
        [],
        "",
        False,
        "List of origins allowed to make cross-origin requests to the REST API.",
    ),
    "CSP_REPORT_ONLY": (
        bool,
        False,
        True,
        False,
        "If true, Content-Security-Policy violations are only reported, never blocked.",
    ),
    "CSRF_COOKIE_NAME": (str, "aurora", "", False, "Name of the CSRF cookie set on clients."),
    "CSRF_COOKIE_SECURE": (
        bool,
        True,
        False,
        False,
        "If true, the CSRF cookie is only sent over HTTPS. Must be true in production.",
    ),
    "CSRF_TRUSTED_ORIGINS": (
        list,
        [],
        [],
        False,
        "List of trusted origins for unsafe (POST/PUT/DELETE) cross-origin requests.",
    ),
    "DATABASE_URL": (
        str,
        "psql://postgres:@postgres:5432/aurora",
        "",
        True,
        "Database connection URL (PostgreSQL), e.g. postgres://user:password@host:5432/aurora. Required in production.",
    ),
    "DEBUG": (
        bool,
        False,
        True,
        False,
        "Django debug mode. Must be false in production. When true, extensive error pages and "
        "debug toolbar are enabled.",
    ),
    "DEBUG_PROPAGATE_EXCEPTIONS": (
        bool,
        False,
        "",
        False,
        "If true, exceptions propagate to the shell/worker instead of being handled by Django.",
    ),
    "DEFAULT_FILE_STORAGE": (
        str,
        "django.core.files.storage.FileSystemStorage",
        "",
        False,
        "Django storage backend for uploaded files (form attachments, images).",
    ),
    "DJANGO_ADMIN_URL": (
        str,
        f"{uuid.uuid4().hex}",
        "",
        True,
        "URL path where the Django admin is exposed. The default is a random value generated at "
        "startup; set it explicitly to a known path such as admin/.",
    ),
    "EMAIL_BACKEND": (
        str,
        "anymail.backends.mailjet.EmailBackend",
        "",
        False,
        "Django email backend. Defaults to AnyMail Mailjet; use "
        "django.core.mail.backends.console.EmailBackend for development.",
    ),
    "EMAIL_FROM_EMAIL": (str, "", "", False, "Default from address for outgoing email."),
    "EMAIL_HOST": (str, "", "", False, "SMTP host used when a non-AnyMail email backend is configured."),
    "EMAIL_HOST_PASSWORD": (str, "", "", False, "SMTP password used when a non-AnyMail email backend is configured."),
    "EMAIL_HOST_USER": (str, "", "", False, "SMTP username used when a non-AnyMail email backend is configured."),
    "EMAIL_PORT": (int, 587, "", False, "SMTP port used when a non-AnyMail email backend is configured."),
    "EMAIL_SUBJECT_PREFIX": (str, "[Aurora]", "", False, "Prefix prepended to the subject of outgoing emails."),
    "EMAIL_TIMEOUT": (int, 30, "", False, "Timeout in seconds for SMTP connections."),
    "EMAIL_USE_LOCALTIME": (bool, False, "", False, "If true, emails use the local timezone instead of UTC."),
    "EMAIL_USE_SSL": (bool, False, "", False, "If true, SMTP uses an implicit SSL connection."),
    "EMAIL_USE_TLS": (bool, True, "", False, "If true, SMTP uses STARTTLS. Disable when EMAIL_USE_SSL is enabled."),
    "EXTRA_AUTHENTICATION_BACKENDS": (
        list,
        [],
        "",
        False,
        "Additional dotted paths of authentication backends appended to the default backend list.",
    ),
    "EXTRA_INSTALLED_APPS": (
        list,
        [],
        "",
        False,
        "Additional Django applications to append to INSTALLED_APPS.",
    ),
    "EXTRA_MIDDLEWARES": (
        list,
        [],
        "",
        False,
        "Additional middleware classes to append to MIDDLEWARE.",
    ),
    "FERNET_KEY": (
        str,
        "",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
        True,
        "Fernet key (32 url-safe base64 bytes) used to encrypt sensitive stored data, e.g. passwords "
        "sent to remote servers. Required in production.",
    ),
    "FRONT_DOOR_ALLOWED_PATHS": (
        str,
        ".*",
        "",
        False,
        "Regex of paths allowed through the front-door maintenance/middleware gate.",
    ),
    "FRONT_DOOR_ENABLED": (bool, False, "", False, "If true, the front-door maintenance gate is active."),
    "FRONT_DOOR_LOG_LEVEL": (str, "ERROR", "", False, "Log level for front-door decisions."),
    "FRONT_DOOR_TOKEN": (
        str,
        f"{uuid.uuid4()}",
        "",
        False,
        "Token used to authenticate requests to the front-door gate. The default is randomly generated at startup.",
    ),
    "GRAPH_API_ENABLED": (
        bool,
        False,
        "",
        False,
        "If true, Microsoft Graph API integration is enabled for user management.",
    ),
    "INTERNAL_IPS": (
        list,
        [],
        ["127.0.0.1", "localhost"],
        False,
        "IPs for which the Django debug toolbar is shown when DEBUG is enabled.",
    ),
    "JWT_LEEWAY": (int, 0, "", False, "Leeway in seconds allowed when validating JWT tokens."),
    "LANGUAGE_CODE": (str, "en-us", "", False, "Default language code of the site, e.g. en-us, ar-ae, fr-fr."),
    "LOG_LEVEL": (
        str,
        "ERROR",
        "DEBUG",
        False,
        "Log level for the aurora application loggers. Use DEBUG while developing.",
    ),
    "LOG_HANDLER": (
        list,
        "console",
        "",
        False,
        "Log handlers used by the application loggers, e.g. console, null.",
    ),
    "MAILJET_API_KEY": (str, "", "", False, "Mailjet API key used by the AnyMail email backend."),
    "MAILJET_SECRET_KEY": (str, "", "", False, "Mailjet secret key used by the AnyMail email backend."),
    "MATOMO_ID": (str, "", "", False, "Matomo site ID for analytics tracking."),
    "MATOMO_SITE": (str, "https://unisitetracker.unicef.io/", "", False, "Matomo tracker base URL."),
    "MEDIA_ROOT": (str, "/tmp/media/", "", False, "Filesystem path where uploaded media files are stored."),
    "MIGRATION_LOCK_KEY": (
        str,
        "django-migrations",
        "",
        False,
        "Redis lock key used to serialize database migrations across instances.",
    ),
    "PRODUCTION_SERVER": (str, "", "", False, "Server name of the production instance, used by the admin sync engine."),
    "PRODUCTION_TOKEN": (
        str,
        "",
        "",
        False,
        "Authentication token of the production instance used by the admin sync engine.",
    ),
    "ROOT_KEY": (str, "", "", False, "Encryption key of the root token used to sign documents and data exports."),
    "ROOT_TOKEN": (
        str,
        "",
        "",
        False,
        "Root token used to sign documents and to authenticate automated data exchange.",
    ),
    "SECRET_KEY": (
        str,
        "",
        "",
        True,
        "Django SECRET_KEY. Required in production; use a long random value and keep it secret.",
    ),
    "SECURE_HSTS_PRELOAD": (
        bool,
        False,
        "",
        True,
        "If true, requests browser preload of the HSTS header. Use only when the whole domain is HTTPS.",
    ),
    "SENTRY_DSN": (str, "", "", False, "Sentry DSN used to send error reports to Sentry."),
    "SENTRY_ENVIRONMENT": (str, "", "", False, "Sentry environment name, e.g. production, staging, develop."),
    "SENTRY_SECURITY_TOKEN": (str, "", "", False, "Token accepted by the Sentry security endpoint of this instance."),
    "SENTRY_SECURITY_TOKEN_HEADER": (
        str,
        "X-Sentry-Token",
        "",
        False,
        "Header name carrying the Sentry security token in security events.",
    ),
    "SESSION_COOKIE_DOMAIN": (
        str,
        "",
        "",
        True,
        "Domain of the session cookie. Leave empty to use the request host.",
    ),
    "SESSION_COOKIE_NAME": (str, "aurora_id", "", False, "Name of the session cookie."),
    "SESSION_COOKIE_SECURE": (
        bool,
        True,
        False,
        True,
        "If true, the session cookie is only sent over HTTPS. Must be true in production.",
    ),
    "SITE_ID": (int, 1, "", False, "ID of the current django.contrib.sites Site record."),
    "SMART_ADMIN_BOOKMARKS": (
        parse_bookmarks,
        "",
        "",
        False,
        "Smart admin bookmarks; each line is a bookmark added to the admin home page.",
    ),
    "STATICFILES_STORAGE": (
        str,
        "django.contrib.staticfiles.storage.StaticFilesStorage",
        "",
        False,
        "Django storage backend for static files. Use ForgivingManifestStaticFilesStorage to version assets.",
    ),
    "STATIC_ROOT": (str, "/tmp/static/", "", False, "Filesystem path where collected static files are stored."),
    "STATIC_URL": (str, "static/", "", False, "URL prefix serving static files."),
    "TRANSLATOR_SERVICE": (
        str,
        "",
        "",
        False,
        "URL of the external translation service used for multilingual content.",
    ),
    "USE_HTTPS": (bool, False, "", False, "If true, the site is served over HTTPS and secure cookies are enforced."),
    "USE_X_FORWARDED_HOST": (
        bool,
        "false",
        "",
        False,
        "If true, Django uses the X-Forwarded-Host header. Enable behind a reverse proxy.",
    ),
}

env = SmartEnv(**OPTIONS)
