# Generated by Django 5.0.13 on 2025-04-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField(blank=True, db_index=True, null=True)),
                ("records", models.IntegerField(blank=True, default=0, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-day",),
                "get_latest_by": "day",
            },
        ),
    ]
