# Generated by Django 5.2 on 2025-04-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registration", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField(blank=True, db_index=True, null=True)),
                ("records", models.IntegerField(blank=True, default=0, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counters",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "ordering": ("-day",),
                "get_latest_by": "day",
                "unique_together": {("registration", "day")},
            },
        ),
    ]
