# Generated by Django 5.0.13 on 2025-04-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("counters", "0001_initial"),
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="counter",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="counters", to="registration.registration"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="counter",
            unique_together={("registration", "day")},
        ),
    ]
