# Generated by Django 5.2 on 2025-04-14 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("flatpages", "0001_initial"),
        ("registration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="registrar",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="flex_form",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.flexform"),
        ),
        migrations.AddField(
            model_name="registration",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="registrations", to="core.project"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="scripts",
            field=models.ManyToManyField(
                blank=True, limit_choices_to={"target": "script"}, related_name="script_for", to="core.validator"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"target": "module"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validator_for",
                to="core.validator",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="welcome_page",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="flatpages.flatpage"
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="registration",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="registration.registration"),
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("name", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="record",
            unique_together={("registration", "unique_field")},
        ),
    ]
