# Generated by Django 5.2.1 on 2025-06-05 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ("pk",)},
        ),
    ]
