# Generated by Django 5.1.7 on 2025-03-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0053_alter_registration_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
