---
name: Build Docker

on:
  workflow_dispatch:
    inputs:
      git_reference:
        description: 'Branch, Tag, or Commit SHA to deploy (e.g., main, develop, v1.0.0, a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0)'
        required: true
        type: string
        default: 'develop'
      tag:
        description: 'Docker tag'
        required: false
        type: string
      latest:
        description: 'Is this the latest docker image'
        required: false
        type: boolean


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  attestations: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.event.inputs.version }}
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Set target input
        id: config
        run: |
          version=$(uvx --with hatch-vcs hatchling metadata version)
          COMMIT_SHA=$(git rev-parse "$GITHUB_SHA")

          git_reference="${{ github.event.inputs.git_reference }}"
          tag="${{ github.event.inputs.tag }}"
          if [ -z "$tag" ]; then
            tag="$git_reference"
          fi
          BUILD_DATE=$(date +"%Y-%m-%d %H:%M")

          echo "git_reference=$git_reference" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "build_date=$BUILD_DATE" >> $GITHUB_OUTPUT
          echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Build and push tag ${{ steps.config.outputs.tag }} (v${{ steps.config.outputs.git_reference }})
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          file: docker/Dockerfile2
          push: true
          labels: |
            "version=${{ steps.config.outputs.version }}"
            "commit=${{ steps.config.outputs.commit_sha }}"
          tags: |
            unicef/hope-aurora:${{ steps.config.outputs.tag }}
            ${{ github.event.inputs.latest == 'true' && 'unicef/hope-aurora:latest' || null}}
          build-args: |
            VERSION=${{ steps.config.outputs.version }}
            BUILD_DATE=${{ steps.config.outputs.build_date }}
            GIT_SHA=${{ steps.config.outputs.commit_sha }}

      - name: Info
        run: |
            echo "::notice title=Tag:: Successfully built unicef/hope-aurora:${{ steps.config.outputs.tag }}"
            echo "::notice title=ImageId:: ${{ steps.build.outputs.imageid }}"
            echo "::notice title=Version :: ${{ steps.config.outputs.version }}"
  appsec_tests:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Package Source code
        continue-on-error: true
        run: |
            zip -r output.zip src

      #- name: Upload zipped folder
      #  uses: actions/upload-artifact@v4
      #  with:
      #      name: zipped-folder
      #      path: output.zip
      - name: Veracode Pipeline
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        continue-on-error: true
        with:
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            file: "output.zip" 
            store_baseline_file: FALES
    #  - name: Veracode Pipeline
    #    continue-on-error: true
    #    run: |
    #      curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    #      unzip -o pipeline-scan-LATEST.zip
    #      java -jar pipeline-scan.jar -vid '${{ secrets.API_ID }}' -vkey '${{ secrets.API_KEY }}' --file "target/dvja-1.0-SNAPSHOT.war" --fail_on_severity "Very High, High"
    #      rm -rf pipeline-scan-LATEST.zip pipeline-scan.jar
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.7
        continue-on-error: true
        with:
            appname: 'HOPE-Aurora'
            createprofile: false
            filepath: 'output.zip'
            vid: '${{ secrets.VERACODE_API_ID }}'
            vkey: '${{ secrets.VERACODE_API_KEY }}'
  
      - name: Veracode SCA
        continue-on-error: true
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
          SRCCLR_SCAN_COLLECTORS: "yarn, pip"
        run: |
          echo "Scanning JS Project"
          curl -sSL  https://download.sourceclear.com/ci.sh | bash -s scan src --allow-dirty

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Veracode Container Scan 
        uses: veracode/container_iac_secrets_scanning@v1.0.4
        continue-on-error: true
        with:
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            command: "scan" 
            type: "image"
            source: ${{ vars.DOCKERHUB_ORGANIZATION }}/unicef/hope-aurora:${{ steps.inputs.outputs.tag }}
            format: "json"
            debug: false
            fail_build: true  
