name: Lint
on:
  push:
    branches:
      - '**'
#  pull_request:
#    branches: [develop, master]
#    types: [synchronize, opened, reopened, ready_for_review]

defaults:
  run:
    shell: bash


concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true


permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  changes:
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name) || github.event_name == 'create'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    defaults:
      run:
        shell: bash
    outputs:
      run_tests: ${{ steps.changes.outputs.run_tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - id: changes
        name: Check for file changes
        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd   # v3.0.0
        with:
          base: ${{ github.ref }}
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  lint:
    #    needs: changes
    runs-on: ubuntu-latest
    #    if: ${{ (!env.ACT) || (github.event.pull_request.draft == false && needs.changes.outputs.lint) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install tox
      - name: Static Code checks
        run: tox -e lint

  mypy:
    #    needs: changes
    #    if: github.event.act || (github.event.pull_request.draft == false && needs.changes.outputs.lint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install tox
      - name: Restore cached vEnv
        id: cache-venv-restore
        uses: actions/cache/restore@v4
        with:
          path: ./.tox
          key: ${{ runner.os }}-venv
      - name: Static Code checks
        run: tox -e mypy
      - name: Save vEnv
        id: cache-venv-save
        uses: actions/cache/save@v4
        with:
          path: ./.tox
          key: ${{ runner.os }}-venv
  package:
    #    needs: changes
    #    if: github.event.act || (github.event.pull_request.draft == false && needs.changes.outputs.lint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install tox
      - name: Check Python Package structure
        run: tox -e pkg_meta
