name: Trivy

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
    env:
      STATIC_URL: /static/
      STATIC_ROOT:
    steps:
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.28.0

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pdm
        run: python -m pip install --upgrade pdm

      - name: Install dependencies
        run: pdm sync

      - name: Scan
        run: |
          trivy fs  \
          --exit-code 0 \
          src/
